CREATE DATABASE customers;

USE customers;

CREATE TABLE users(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(255),
PRIMARY KEY (ID)
);

CREATE TABLE address(
ID INT NOT NULL AUTO_INCREMENT,
STREET_ADDRESS VARCHAR(100),
ADDRESS_LINE2 VARCHAR(20),
CITY VARCHAR(30),
STATE VARCHAR(20),
ZIPCODE INT (10),
USER_ID INT,
FOREIGN KEY (user_id) REFERENCES USERS (ID)
);

CREATE TABLE cards(
ID INT NOT NULL AUTO_INCREMENT,
CARD_NUM INT (19),
EXP_DATE DATE,
CVV INT (3),
ZIPCODE INT (10),
USER_ID INT,
FOREIGN KEY (user_id) REFERENCES USERS (ID)
);